quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bench
quarkus.datasource.password=bench123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/benchmark
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.http.port=5000
quarkus.http.host=0.0.0.0
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.log.console.level=INFO
quarkus.log.category."dev.benchmark".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=WARN